# Generated by Django 3.1.7 on 2022-06-24 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last_login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('mobile_no', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('is_user_admin', models.BooleanField(default=False)),
                ('is_marketer', models.BooleanField(default=False)),
                ('is_publisher', models.BooleanField(default=False)),
                ('is_accountant', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('district', models.CharField(max_length=252)),
                ('taluka', models.CharField(max_length=252)),
                ('address', models.TextField()),
                ('mbno', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post_image', models.ImageField(upload_to='post-images')),
            ],
        ),
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_admin.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('user_admin.account',),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_admin.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('user_admin.account',),
        ),
        migrations.CreateModel(
            name='Marketer',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_admin.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('user_admin.account',),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_admin.account')),
            ],
            options={
                'abstract': False,
            },
            bases=('user_admin.account',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('bill_status', models.BooleanField(default=False)),
                ('total_bill_amt', models.IntegerField()),
                ('mode_of_pay', models.CharField(max_length=100)),
                ('trans_id', models.CharField(max_length=100)),
                ('cheque_image', models.ImageField(blank=True, null=True, upload_to='cheque-images')),
                ('bill_receipt', models.ImageField(blank=True, null=True, upload_to='bill-receipts')),
                ('release_order', models.ImageField(blank=True, null=True, upload_to='release-orders')),
                ('signed_release_order', models.ImageField(blank=True, null=True, upload_to='signed-release-orders')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.client')),
                ('marketer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.marketer')),
            ],
        ),
        migrations.CreateModel(
            name='Advt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='ad-images')),
                ('ad_pub_date', models.DateTimeField()),
                ('ad_pub_actual_date', models.DateTimeField(blank=True, null=True)),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.order')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.adtype')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='marketer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.marketer'),
        ),
    ]
