# Generated by Django 3.1.7 on 2022-06-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_app_admin',
            new_name='is_user_admin',
        ),
    ]
