# Generated by Django 3.1.7 on 2022-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trans_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
