# Generated by Django 3.1.7 on 2022-06-18 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_auto_20220617_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252)),
                ('district', models.CharField(max_length=252)),
                ('taluka', models.CharField(max_length=252)),
                ('address', models.TextField()),
                ('mbno', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_status', models.BooleanField(default=False)),
                ('total_bill_amt', models.IntegerField()),
                ('mode_of_pay', models.CharField(max_length=100)),
                ('trans_id', models.CharField(max_length=100)),
                ('bill_receipt', models.ImageField(default=None, upload_to='bill-receipts')),
                ('release_order', models.ImageField(default=None, upload_to='release-orders')),
                ('signed_release_order', models.ImageField(default=None, upload_to='signed-release-orders')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.client')),
                ('marketer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.marketer')),
            ],
        ),
        migrations.CreateModel(
            name='Advt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('ad_image', models.ImageField(upload_to='ad-images')),
                ('ad_pub_date', models.DateTimeField(verbose_name='ad_pub_date')),
                ('ad_pub_actual_date', models.DateTimeField(verbose_name='ad_pub_actual_date')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.adtype')),
            ],
        ),
        migrations.AddField(
            model_name='adtype',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.order'),
        ),
    ]
