# Generated by Django 3.1.7 on 2022-06-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_auto_20220618_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='bill-receipts'),
        ),
        migrations.AlterField(
            model_name='order',
            name='release_order',
            field=models.ImageField(blank=True, null=True, upload_to='release-orders'),
        ),
        migrations.AlterField(
            model_name='order',
            name='signed_release_order',
            field=models.ImageField(blank=True, null=True, upload_to='signed-release-orders'),
        ),
    ]
