# Generated by Django 3.1.7 on 2022-06-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_auto_20220618_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='marketer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.marketer'),
        ),
    ]
