# Generated by Django 3.1.7 on 2022-06-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_auto_20220624_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adtype',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
