# Generated by Django 3.1.7 on 2022-06-21 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_client_marketer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adtype',
            name='order_id',
        ),
        migrations.AddField(
            model_name='advt',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.order'),
        ),
    ]
