# Generated by Django 3.1.7 on 2022-06-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0006_auto_20220624_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('in_review', 'In Review'), ('fresh', 'Fresh'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='fresh', max_length=100),
        ),
    ]
