# Generated by Django 3.1.7 on 2022-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0006_auto_20220621_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='adtype',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
