# Generated by Django 3.1.7 on 2022-06-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0007_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode_of_pay',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque')], max_length=100, null=True),
        ),
    ]
