# Generated by Django 3.1.7 on 2022-06-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0007_adtype_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='ad_pub_actual_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ad_pub_actual_date'),
        ),
    ]
