# Generated by Django 3.1.7 on 2022-06-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0008_auto_20220621_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='ad_image',
            field=models.ImageField(blank=True, null=True, upload_to='ad-images'),
        ),
    ]
