# Generated by Django 3.1.7 on 2022-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0009_auto_20220621_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='ad_pub_actual_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advt',
            name='ad_pub_date',
            field=models.DateTimeField(),
        ),
    ]
