# Generated by Django 3.1.7 on 2022-06-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0010_auto_20220626_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode_of_pay',
            field=models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('none', 'None')], default='none', max_length=100),
        ),
    ]
