# Generated by Django 3.1.7 on 2022-06-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0011_auto_20220626_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='desc',
            field=models.TextField(verbose_name='Ad Description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('In Review', 'In Review'), ('Fresh', 'Fresh'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='fresh', max_length=100),
        ),
    ]
