# Generated by Django 3.1.7 on 2022-06-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0013_auto_20220627_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='advt',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
