# Generated by Django 3.1.7 on 2022-06-29 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0015_auto_20220628_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advts', to='user_admin.order'),
        ),
    ]
