# Generated by Django 3.1.7 on 2022-06-29 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0016_auto_20220629_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.order'),
        ),
    ]
