# Generated by Django 3.1.7 on 2022-06-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0019_auto_20220629_0045'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdLoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='advt',
            name='type',
        ),
        migrations.DeleteModel(
            name='AdType',
        ),
        migrations.AddField(
            model_name='location',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.type'),
        ),
        migrations.AddField(
            model_name='adloc',
            name='advt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.advt'),
        ),
        migrations.AddField(
            model_name='adloc',
            name='loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.location'),
        ),
    ]
