# Generated by Django 3.1.7 on 2022-06-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0020_auto_20220630_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='type',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
