# Generated by Django 3.1.7 on 2022-06-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0021_auto_20220630_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
