# Generated by Django 3.1.7 on 2022-06-30 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0022_location_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adloc',
            name='advt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_locs', to='user_admin.advt'),
        ),
    ]
