# Generated by Django 3.1.7 on 2022-06-30 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0023_auto_20220630_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adloc',
            old_name='loc',
            new_name='location',
        ),
    ]
