# Generated by Django 4.0.5 on 2022-06-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0025_advt_ad_amt_alter_account_id_alter_adloc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='ad_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
