# Generated by Django 4.0.5 on 2022-06-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0026_alter_advt_ad_amt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='ad_amt',
            field=models.IntegerField(default=0),
        ),
    ]
