# Generated by Django 4.0.5 on 2022-07-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0027_alter_advt_ad_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='jlsfd', max_length=252),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='whatsapp_mbno',
            field=models.CharField(default=2123123, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
