# Generated by Django 4.0.5 on 2022-07-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0028_client_company_name_client_whatsapp_mbno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='whatsapp_mbno',
            field=models.CharField(max_length=30),
        ),
    ]
