# Generated by Django 4.0.5 on 2022-07-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0029_alter_client_whatsapp_mbno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='whatsapp_mbno',
        ),
    ]
