# Generated by Django 4.0.5 on 2022-07-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0030_remove_client_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(default='sdfj', max_length=252),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='gst_number',
            field=models.CharField(default=2121, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='whatsapp_mbno',
            field=models.CharField(default='sdfj', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
