# Generated by Django 4.0.5 on 2022-07-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0031_client_company_name_client_gst_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='ad_pub_date',
            field=models.DateTimeField(unique=True),
        ),
    ]
