# Generated by Django 4.0.5 on 2022-07-01 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0032_alter_advt_ad_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_alloted_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_allowed_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.admin'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_decision',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_requested',
            field=models.BooleanField(default=False),
        ),
    ]
