# Generated by Django 4.0.5 on 2022-07-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0034_order_discount_req_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discounted_new_bill_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
