# Generated by Django 4.0.5 on 2022-07-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0035_order_discounted_new_bill_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='final_bill_amt',
            field=models.IntegerField(default=0),
        ),
    ]
