# Generated by Django 4.0.5 on 2022-07-03 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0036_order_final_bill_amt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_allowed_admin',
            new_name='discount_allowed_or_rejected_admin',
        ),
    ]
