# Generated by Django 4.0.5 on 2022-07-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0037_rename_discount_allowed_admin_order_discount_allowed_or_rejected_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_mah',
            field=models.BooleanField(default=False),
        ),
    ]
