# Generated by Django 4.0.5 on 2022-07-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0038_location_is_mah'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst_final_bill_amt',
            field=models.IntegerField(default=0),
        ),
    ]
