# Generated by Django 4.0.5 on 2022-07-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0039_order_gst_final_bill_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bill_status_msg',
            field=models.CharField(default='', max_length=200),
        ),
    ]
