# Generated by Django 4.0.5 on 2022-07-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0041_remove_order_bill_receipt_remove_order_cheque_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_accepted_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
