# Generated by Django 4.0.5 on 2022-07-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0043_order_gst_allowed_or_rejected_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bill_status_msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
