# Generated by Django 4.0.5 on 2022-07-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0045_client_client_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agency_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='agency_district',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='agency_email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='agency_mbno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='agency_name',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='agency_taluka',
            field=models.CharField(blank=True, max_length=252, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='agency_whatsapp_mbno',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
