# Generated by Django 4.0.5 on 2022-07-27 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0046_client_agency_address_client_agency_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='company_name',
            new_name='client_company_name',
        ),
    ]
