# Generated by Django 4.0.5 on 2022-07-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0048_rename_address_client_client_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='agency_mbno',
            new_name='agency_mobile_no',
        ),
    ]
