# Generated by Django 4.0.5 on 2022-07-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0049_rename_agency_mbno_client_agency_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='agency_gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
