# Generated by Django 4.0.5 on 2022-07-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0051_alter_client_client_gst_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_gst_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
