# Generated by Django 4.0.5 on 2022-07-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0052_alter_client_client_gst_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(blank=True, max_length=252, null=True)),
                ('agency_mobile_no', models.CharField(blank=True, max_length=30, null=True)),
                ('agency_district', models.CharField(blank=True, max_length=252, null=True)),
                ('agency_taluka', models.CharField(blank=True, max_length=252, null=True)),
                ('agency_address', models.TextField(blank=True, null=True)),
                ('agency_whatsapp_mbno', models.CharField(blank=True, max_length=30, null=True)),
                ('agency_email', models.EmailField(blank=True, max_length=60, null=True)),
                ('agency_gst_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='agency_address',
        ),
        migrations.RemoveField(
            model_name='client',
            name='agency_district',
        ),
        migrations.RemoveField(
            model_name='client',
            name='agency_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='agency_gst_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='agency_mobile_no',
        ),
        migrations.RemoveField(
            model_name='client',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='agency_taluka',
        ),
        migrations.RemoveField(
            model_name='client',
            name='agency_whatsapp_mbno',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
        migrations.AddField(
            model_name='client',
            name='is_agency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='client',
            name='agency_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.agency'),
        ),
    ]
