# Generated by Django 4.0.5 on 2022-07-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0053_agency_remove_client_agency_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_mobile_no',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='agency_whatsapp_mbno',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
