# Generated by Django 4.0.5 on 2022-07-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0054_alter_agency_agency_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='agency_whatsapp_mbno',
            new_name='agency_whatsapp_mobile_no',
        ),
    ]
