# Generated by Django 4.0.5 on 2022-07-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0055_rename_agency_whatsapp_mbno_agency_agency_whatsapp_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='marketer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user_admin.marketer'),
            preserve_default=False,
        ),
    ]
