# Generated by Django 4.0.5 on 2022-07-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0061_rename_client_address_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advt',
            name='ad_pub_date',
            field=models.DateTimeField(blank=True, null=True, unique=True),
        ),
    ]
