# Generated by Django 4.0.5 on 2022-07-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0062_alter_advt_ad_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='agency_discount_amt',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='agency_discount_given',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='agency_discount_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
